name: Test and Deploy to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      

      - name: Run FastAPI server and tests
        env:
          AGENTOPS_API_KEY: ${{ secrets.AGENTOPS_API_KEY }}
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
          TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
          SCRAPEGRAPH_API_KEY: ${{ secrets.SCRAPEGRAPH_API_KEY }}
          SCORE_THRESH: ${{ vars.SCORE_THRESH }}
          TOP_RECOMMENDATIONS_NUM: ${{ vars.TOP_RECOMMENDATIONS_NUM }}
          LLM: ${{ vars.LLM }}
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          uvicorn src.main:app --host 0.0.0.0 --port 5000 &
          SERVER_PID=$!
          sleep 7
          pytest src/unit_test
          kill $SERVER_PID

      - name: Set up Git
        run: |
          git config --global user.email "ai388981@gmail.com"
          git config --global user.name "AhmedAyman77"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://A7medAyman:${HF_TOKEN}@huggingface.co/spaces/A7medAyman/Agentic-Procurement-Assistant
          git push hf main --force